### ISSUE TITLE
Not updated

### ISSUE THREAD

**Issue by avipars** [madisvain/exchangeratesapi#108]
Last update is 12/31/2020

and today is 1/3/2021

**Comment by micahmills** [comment]
It looks like the data source https://www.ecb.europa.eu/stats/eurofxref/eurofxref-hist-90d.xml isn't updated beyond 12/31/20. This might be because of the new year holiday and the weekend. I am hoping it updates later today, and the problem will be solved.

**Comment by avipars** [comment]
Thanks ;)
Makes sense

**Comment by micahmills** [comment]
It looks like it is working now.

**Comment by ngosang** [comment]
![imagen](https://user-images.githubusercontent.com/10577978/106359516-a2b17780-6313-11eb-827e-f3a88b3fc9ad.png)


https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html
