### ISSUE TITLE
JPY base not working when symbols are specified

### ISSUE THREAD

**Issue by randomish** [madisvain/exchangeratesapi#12]
This isn't working for me:
https://exchangeratesapi.io/api/latest?base=JPY&symbols=EUR,NOK

The equivalent URL used to work in the old fixer.io API.

**Comment by madisvain** [comment]
@randomish the issue in question has been fixed. Sorry for the delay - I was in the middle of rewriting the service and deploying it to Heroku.

There will be a deploy to Heroku button also available shortly.

Please let me know if there is anything else I can do for you.
