### ISSUE TITLE
Latest Rates Endpoint base currency error

### ISSUE THREAD

**Issue by zyLiu-aftership** [madisvain/exchangeratesapi#123]
I've been having a play with your Exchange Rate API - a great tool, thanks so much!

One thing I noticed is that there's a problem that the base parameter cannot be modified.

If I use the default base currency EUR, the request is OK. But when I change my base parameter, for example, use the following request.

`http://api.exchangeratesapi.io/v1/latest?access_key=access_key&base=GBP&symbols=USD,AUD,CAD,PLN,MXN`

It made a mistake as follows.
`{
    "error": {
        "code": "base_currency_access_restricted",
        "message": "An unexpected error ocurred. [Technical Support: support@apilayer.com]"
    }
}`

Not sure why this is, did I use it the wrong way? We look forward to your reply. thanks so much!

**Comment by dropbeardan** [comment]
Are you perchance... using the free service?

They recently locked this as a paid feature IIRC

This took me by surprise too when it happened but have a look at the plans again since they have significantly changed.

**Comment by zyLiu-aftership** [comment]
@dropbeardan Use of the free account, is my problem, thank you for your reply.
