### ISSUE TITLE
Clarification for exchange rates

### ISSUE THREAD

**Issue by reckter** [madisvain/exchangeratesapi#132]
I couldn't find a clarification in the API, for which direction it provides, so: 

If I want to download exchange rates for converting USD to EUR:
I use `/latest?base=EUR`.
(Or do I use `/latest?base=USD`?)

And then I take the value that is returned or `USD` and multiply my `amountInEUR` with it to get `amountInUSD`.

We want to make sure that we take the correct value, because direction matters for exchange rates (exchange rate from EUR to USD, might differ from USD to EUR).

**Comment by lucasRolff** [comment]
If you want to convert 100 USD to EUR you can use base=USD and multiply the EUR value you get (e.g. `0.9283*100`)
You can also use EUR as base and reverse the calculation, e.g. if using EUR as base, USD would return 1.0772, so you'd do:
`100 / 1.0772 = 92.833`.
