### ISSUE TITLE
incompatibile base rate

### ISSUE THREAD

**Issue by pine3ree** [madisvain/exchangeratesapi#6]
Hello,
1st things 1st: thanks!

There are a few currencies that are not reliable because of their distance from the EUR value. For instance the Indonesian Rupiah

https://exchangeratesapi.io/api/latest?base=IDR

so, while it makes sense to convert EUR to IDR (*17059.77), the inverse is not true (should be ~ 0,000059, but the api is limited to 4 decimals)

kind regards

**Comment by madisvain** [comment]
@pine3ree thanks for this report - I will take a look and push a fix for this within a few days. By the end of this week for sure.

**Comment by pine3ree** [comment]
Thanks, @madisvain 
No rush here....I mostly use EUR as the base currency and parse the ECB xml directly as first option. Best regards.

**Comment by pine3ree** [comment]
Thanks @madisvain, I think that 8 decimals would probably have sufficed, but then I remember that magento supports up to 12. kind regards, maks.

**Comment by pine3ree** [comment]
oh...i forgot...there is also this xml USD related rates list available at [Yahoo! Finance](https://finance.yahoo.com/webservice/v1/symbols/allcurrencies/quote)
with update timestamp for each conversion rate

**Comment by madisvain** [comment]
Hei - did not know about it. And it support JSON also actually:
https://finance.yahoo.com/webservice/v1/symbols/allcurrencies/quote?format=json

No CORS support and I can not see an option for specifying any dates sadly. Maybe you know more? We could possibly support multiple sources.

**Comment by pine3ree** [comment]
Hello @madisvain ,

I believe it can be done via YQL query language (see an example in magento source code https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Directory/Model/Currency/Import/YahooFinance.php)
