### ISSUE TITLE
Single "symbol" not working

### ISSUE THREAD

**Issue by ThunderbyteComputer** [madisvain/exchangeratesapi#9]
If only a single "symbol" is given, there is an error:

Working (two symbols):

https://exchangeratesapi.io/api/latest?base=USD&symbols=CHF,USD

Giving Error (single symbol):
https://exchangeratesapi.io/api/latest?base=USD&symbols=CHF

**Comment by madisvain** [comment]
@ThunderbyteComputer thank you for reporting this. The issue has been resolved and a fix deployed.
